# nome do processo
name: CI
# métodos que iremos checar
on: [push, pull_request]
# tarefas a serem feitas
jobs:
  # nome da primeira tarefa
  test-frontend:
    # sistema operacional que será usado na imagem
    runs-on: ubuntu-latest
    # passo a passo do nosso projeto
    steps:
      # dar pull na máquina do nosso código
      - name: Checkout code
        uses: actions/checkout@v2
      # instalar o Node.js na versão correta
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21.7.0"
      # instalar as dependências
      - name: Install dependencies
        run: npm install
      # rodar os testes
      - name: Run frontend tests
        run: npm test
